### PR TITLE
[BAHIR-92] Let update-doc.sh also update docs for Apache Flink extensions

### PR DESCRIPTION
**Pull request by tzulitai**
This PR lets the `update-doc.sh` script also sync Apache Flink docs from `bahir-flink` README sources to the site docs.

It also attempts to refactor the script so that it is more friendly for adding new platform extensions to Bahir's document infrastructure in the future.

The generated Flink docs by the script will be submitted as a separate PR.

### CODE REVIEW

**Comment by ckadner** [comment]
@tzulitai -- Thanks for your PR. Your changes look good but I still need to run a few tests to sign off on it.

In the meantime, could you double quote all the path and file name variables to prevent globbing/word splitting. Please run the script through a Shell script lint tool to find all the occurrences. A free online tool is https://www.shellcheck.net/

**Comment by tzulitai** [comment]
Thanks for the review @ckadner!

> In the meantime, could you double quote all the path and file name variables to prevent globbing/word splitting. Please run the script through a Shell script lint tool to find all the occurrences. A free online tool is https://www.shellcheck.net/

Will do!

**Comment by tzulitai** [comment]
@ckadner I've addressed your comments. Please let me know if there's any other issues to be addressed.

**Comment by ckadner** [comment]
@tzulitai -- I seem to have picked the wrong time of day to merge your PR, for about an hour now I am getting this error. I will try again tomorrow.

```Bash
$ git fetch --all
Fetching origin
fatal: unable to access 'https://git-wip-us.apache.org/repos/asf/bahir-website.git/': SSLRead() return error -9806
error: Could not fetch origin
...
```

**Comment by tzulitai** [comment]
@ckadner no problem! Thanks for letting me know.

**Pull request closed without merging**
